name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.7.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "mim-jdp"
          heroku_email: ${{secrets.HEROKU_API_MAIL}}
          usedocker: true
        env:
          MONGO_DB_URI: ${{secrets.MONGO_DB_URI}}
          ENV: ${{secrets.ENV}}
          PORT: ${{secrets.PORT}}
          SECRET_KEY: ${{secrets.SECRET_KEY}}
